---
title: "Untitled"
author: "Puwen Tan"
date: "2021/6/20"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="D:/HSC_Autophagy/Markdown/3.scATFR/scATFR") 
```

```{r}
library(Seurat)
WT_matrix <- Seurat::Read10X("../ext_data/Batf3_KO/raw_data/WT/")
WT_exp <- WT_matrix$`Gene Expression`
colnames(WT_exp) <- paste("WT_",colnames(WT_exp),sep="")
WT <- CreateSeuratObject(counts = WT_exp, project = "WT")

Batf3_matrix <- Seurat::Read10X("../ext_data/Batf3_KO/raw_data/Batf3_KO/")
Batf3_exp <- Batf3_matrix$`Gene Expression`
colnames(Batf3_exp) <- paste("Batf3_KO_",colnames(Batf3_exp),sep="")
Batf3 <- CreateSeuratObject(counts = Batf3_exp, project = "Batf3_KO")
Batf3_KO <- merge(x = WT, y=Batf3, project = "Batf3_KO")

Batf3_KO[["percent.mt"]] <- PercentageFeatureSet(Batf3_KO, pattern = "^mt-")
head(Batf3_KO@meta.data, 5)

plot1 <- FeatureScatter(Batf3_KO, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(Batf3_KO, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
VlnPlot(Batf3_KO, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Batf3_KO <- subset(Batf3_KO, subset = nFeature_RNA > 1000 & nFeature_RNA < 5000 & percent.mt < 10)
VlnPlot(Batf3_KO, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)


Batf3_KO <- NormalizeData(Batf3_KO, normalization.method = "LogNormalize", scale.factor = 10000)
Batf3_KO <- FindVariableFeatures(Batf3_KO, selection.method = "vst", nfeatures = 2000)
Batf3_KO <- ScaleData(Batf3_KO, use.umi=T)
Batf3_KO <- RunPCA(Batf3_KO, features = VariableFeatures(object = Batf3_KO))
DimPlot(Batf3_KO, reduction = "pca")
Batf3_KO <- FindNeighbors(Batf3_KO, dims = 1:50)
Batf3_KO <- FindClusters(Batf3_KO)
Batf3_KO <- RunTSNE(object = Batf3_KO, dims.use = 1:50)
DimPlot(Batf3_KO, reduction = "tsne", label = TRUE, label.size=4)
#Cdh1---epithelial cells
FeaturePlot(Batf3_KO, reduction = "tsne",features = "Batf3",split.by = "orig.ident")
FeaturePlot(Batf3_KO, reduction = "tsne",features = "Nkx2-1")

Batf3_KO <- RunUMAP(Batf3_KO, umap.method ="uwot", dims = 1:50)
DimPlot(Batf3_KO, reduction = "umap", label = TRUE, label.size=4)
FeaturePlot(Batf3_KO, reduction = "umap",features = "Batf3",split.by = "orig.ident")

Batf3_KO_counts <- as.matrix(Seurat::GetAssayData(Batf3_KO, assay = "RNA", slot = "counts"))
saveRDS(Batf3_KO_counts,"../ext_data/Batf3_KO/raw_data/Batf3_KO_cell_counts.rds")
saveRDS(Batf3_KO@meta.data,"../ext_data/Batf3_KO/raw_data/Batf3_KO_cell_metadata.rds")


```
### infer GRNs 
```{r}
library(scATFR)
batf3_exp <- readRDS("/media/hobart/s4T2/tpw/4.PIDC/ext_data/Batf3_KO_cell_counts.rds")
atfr <- scATFR(exp_data = batf3_exp,regulons=list(Batf3="Batf3"))
time_up <- list()
for(i in c("pcor","genie3","sclink")){
  st <- Sys.time()
  atfr <- inferGRNs(x = atfr,method=i, use_regulator = "Batf3",ncores = 30)
  diff_time <- Sys.time()-st
  time_up[[i]] <- diff_time
  saveRDS(atfr,paste("/media/hobart/s4T2/tpw/4.PIDC/GRNs/batf3_KO/GRN_",i,".rds",sep=""))
}

```



### 2. regulon activity
```{r}
atfr <- readRDS("../ext_data/Batf3_KO/")

batf3_exp <- readRDS("/media/hobart/s4T2/tpw/4.PIDC/ext_data/Batf3_KO_cell_counts.rds")
PIDC_batf3 <- PIDC::PIDC(expMat = batf3_exp,exp_percent = 0.05,ncores = 30)

```






