---
title: "Crop-seq"
author: "Puwen Tan"
date: "2021/6/14"
output: html_document
---
#### 1. CROP-seq
```{r}
library(data.table)
data <- data.table::fread("../ext_data/CROPseq/raw_data/CROP-seq_Jurkat_TCR.digital_expression.500genes.only_assigned.csv",sep=",",data.table=F)
meta_data <- as.data.table(t(data[1:4,]),keep.rownames = TRUE)
colnames(meta_data) <- as.character(meta_data[1,])
meta_data <- meta_data[-1,]
duplicated_cells <- meta_data[duplicated(meta_data$cell),]
meta_data <- tibble(meta_data) %>% filter(!(cell %in% duplicated_cells$cell))

dir.create("../ext_data/CROPseq/expression_data/")
saveRDS(meta_data,"../ext_data/CROPseq/raw_data/count_metadata.rds")
fwrite(meta_data,"../ext_data/CROPseq/expression_data/count_metadata.txt",sep="\t")


exp_data <- data[-c(1:5),]
cols <- c("GENE",meta_data$cell)
colnames(exp_data) <- c("GENE",as.character(data[2,-1]))
exp_data <- exp_data[,..cols]
saveRDS(exp_data,"../ext_data/CROPseq/raw_data/count_matrix.rds")
fwrite(exp_data,"../ext_data/CROPseq/expression_data/count_matrix.txt",sep="\t")

# unstimulated cells
library(dplyr)
unstimulated_metadata <- tibble(meta_data) %>% filter(condition=="unstimulated") %>%
cols <- c("GENE",unstimulated_metadata$cell)
unstimulated_count <- tibble(exp_data) %>% filter(GENE %in% unstimulated_metadata$gene) %>%
  select(c("GENE",unstimulated_metadata$cell))
CTRL_cells <- unstimulated_metadata %>% filter(gene == "CTRL")
essten_gene <- c("MVD","TUBB","DHODH")
TF_cells <- unstimulated_metadata %>% filter(!(gene %in% essten_gene))

genes <- names(table(TF_cells$grna))
genes <- genes[-grep("^CTRL",genes)]
outlist <- list()
for(i in genes){
  RUNX1_cells <- unstimulated_metadata %>% filter(grna == i)
  Gene <- unique(RUNX1_cells$gene)
  RUNX1_expression <- unstimulated_count %>% filter(GENE == Gene) %>%
  select(RUNX1_cells$cell) %>% as.numeric()
  RUNX1_CTRL_expression <- unstimulated_count %>% filter(GENE == Gene) %>%
  select(CTRL_cells$cell) %>% as.numeric()
  p_val <- t.test(RUNX1_expression,RUNX1_CTRL_expression)$p.value
  names(p_val) <- i
  logFC <- log2(mean(RUNX1_expression)/mean(RUNX1_CTRL_expression))
  outfrm <- data.frame(gene=i,logFC=logFC, pval=p_val)
  outlist[[i]] <- outfrm
}
outlist <- rbindlist(outlist)
outlist$padj <- p.adjust(outlist$pval,method="BH")
outlist_diff <- tibble(outlist) %>% filter(padj<0.2 & logFC < -1)
dim(unstimulated_metadata[unstimulated_metadata$grna %in% outlist_diff$gene,])

select_metadata <- unstimulated_metadata %>% filter(grna %in% outlist_diff$gene)
select_metadata <- rbind(select_metadata, CTRL_cells)
fwrite(select_metadata,"../ext_data/CROPseq/expression_data/diff_count_metadata.txt",sep="\t")

select_counts <- tibble(exp_data) %>% select(c("GENE",select_metadata$cell))
fwrite(select_counts,"../ext_data/CROPseq/expression_data/diff_count_matrix.txt",sep="\t")

```

#### 1.2 Run scATR

```{r}
library(scATFR)
count_mat <- read.table("../ext_data/CROPseq/expression_data/diff_count_matrix.txt",sep="\t",header=T,row.names = 1)
col_data <- read.table("../ext_data/CROPseq/expression_data/diff_count_metadata.txt",sep="\t",header=T)
row.names(col_data) <- col_data$cell

library(dplyr)
regulons <- dorothea_regulons$hs_regulons
regulons <- dfToList(df = regulons, tf_col = "tf",target_col = "target")
atfr <- scATFR(exp_data = count_mat,col_data = col_data, regulons = regulons)
st <- Sys.time()
atfr <- inferGRNs(x = atfr, method="sctenifoldnet", ncores=6)
Sys.time()-st

atfr <- filterRegulons(x=atfr, ncores=6)
atfr <- regulonActivity(atfr, method="viper",ncores=6)
atfr_mat <- assay(altExp(atfr,"atfr"))


```






#### 2. 


































